modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cmsall"
version = "${version}"
displayName = "CM'sALL"
authors = "G.Vael"
description = '''
Unified MineAll / CutAll / DigAll chain-harvest mod.
'''
logoFile = "assets/cmsall/icon.png"

[[dependencies.cmsall]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cmsall]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cmsall]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
